version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  quarkus-native:
      image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/quarkus_native:quarkus-native-image-simplified
      environment:
        - API_URL=http://nginx:80
        - FILE_IMPORTER_ENABLED=true
        - FILE_IMPORTER_LOCATION_TYPE=URI
        - FILE_IMPORTER_IMPORT_LOCATION=/import
        - FILE_IMPORTER_DONE_LOCATION=/done
        - FILE_IMPORTER_WILDCARD=.+\.([Pp][Dd][Ff])\s*$
        - FILE_IMPORTER_CONFIG_NAME=testURIImporterConfig
        - FILE_IMPORTER_BATCH_SIZE=2000
        - FILE_IMPORTER_INTERVAL_SEC=30
        - FILE_IMPORTER_SLEEP_BEFORE_IMPORT=2
        - FILE_IMPORTER_SLEEP_TIME=10
        - FILE_IMPORTER_THREAD_COUNT=8
        - API_USERNAME=FHNW_SERVICE_MANAGER
        - API_PASSWORD=FezNNtMuauSxHGocPSF7
      volumes:
        - C:\temp\FILEIMPORTER_PDF\import:/import
        - C:\temp\FILEIMPORTER_PDF\done:/done
      depends_on:
        - nginx
  quarkus-jvm:
      image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/quarkus_jvm:quarkus-native-image-simplified
      environment:
        - API_URL=http://nginx:80
        - FILE_IMPORTER_ENABLED=true
        - FILE_IMPORTER_LOCATION_TYPE=URI
        - FILE_IMPORTER_IMPORT_LOCATION=/import
        - FILE_IMPORTER_DONE_LOCATION=/done
        - FILE_IMPORTER_WILDCARD=.+\.([Pp][Dd][Ff])\s*$
        - FILE_IMPORTER_CONFIG_NAME=testURIImporterConfig
        - FILE_IMPORTER_BATCH_SIZE=2000
        - FILE_IMPORTER_INTERVAL_SEC=30
        - FILE_IMPORTER_SLEEP_BEFORE_IMPORT=2
        - FILE_IMPORTER_SLEEP_TIME=10
        - FILE_IMPORTER_THREAD_COUNT=8
        - API_USERNAME=FHNW_SERVICE_MANAGER
        - API_PASSWORD=FezNNtMuauSxHGocPSF7
      volumes:
        - C:\temp\FILEIMPORTER_PDF\import:/import
        - C:\temp\FILEIMPORTER_PDF\done:/done
      depends_on:
        - nginx


  spring-native-simple:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/spring_native:spring-native-image-simplified
    volumes:
      - C:\temp\FILEIMPORTER_PDF\import:/import
      - C:\temp\FILEIMPORTER_PDF\done:/done
    depends_on:
      - nginx
  spring-jvm-simple:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/spring_jvm:spring-native-image-simplified
    volumes:
      - C:\temp\FILEIMPORTER_PDF\import:/import
      - C:\temp\FILEIMPORTER_PDF\done:/done
    depends_on:
      - nginx

  Micronaut-jvm:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/micronaut_jvm:micronaut-image
    volumes:
      - C:\temp\FILEIMPORTER_PDF\import:/import
      - C:\temp\FILEIMPORTER_PDF\done:/done
    depends_on:
      - nginx
  Micronaut-native:
    image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/micronaut_native:micronaut-native-image
    volumes:
      - C:\temp\FILEIMPORTER_PDF\import:/import
      - C:\temp\FILEIMPORTER_PDF\done:/done
    depends_on:
      - nginx

  # FÃ¼r den Bericht vergleichen wir spring,Quarkus, Micronaut jeweils in der JVM und Native Variante. Die Baseline jvm wird nur mit baseline-native verglichen.
  #Spring-JVM-Baseline:
  #  image: cr.gitlab.fhnw.ch/ip5-24vt/fileimporter/spring_native:baseline
  #  volumes:
  #    - C:\temp\FILEIMPORTER_PDF\import:/import
  #    - C:\temp\FILEIMPORTER_PDF\done:/done
  #  depends_on:
  #    - nginx
